# Generated by Django 3.2.7 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charitytbl',
            name='date',
        ),
        migrations.AddField(
            model_name='assigntbl',
            name='fdreq_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
